apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tvwc6ix3c-go 
  janus-idp.io/tekton: tvwc6ix3c-go
  backstage.io/kubernetes-id: tvwc6ix3c-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tvwc6ix3c-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml