apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tvwc6ix3c-go
  janus-idp.io/tekton: tvwc6ix3c-go
  backstage.io/kubernetes-id: tvwc6ix3c-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tvwc6ix3c-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
